import {Nunito_Sans, Inter} from "next/font/google";
import "./globals.css";

const NunitoSans = Nunito_Sans({ subsets: ["latin"], varaiable: '--font-NunitoSans'});
const FontInter = Inter({ subsets: ["latin"], varaiable: '--font-inter'});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${FontInter.className} ${NunitoSans.className}`}>{children}</body>
    </html>
  );
}
